// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestWpfApp.Data.Context;

#nullable disable

namespace TestWpfApp.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("GroupSpeciality", b =>
                {
                    b.Property<int>("GroupsGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecialitiesSpecialityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupsGroupId", "SpecialitiesSpecialityId");

                    b.HasIndex("SpecialitiesSpecialityId");

                    b.ToTable("GroupSpeciality");
                });

            modelBuilder.Entity("SpecialityTheme", b =>
                {
                    b.Property<int>("SpecialitiesSpecialityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThemesThemeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SpecialitiesSpecialityId", "ThemesThemeId");

                    b.HasIndex("ThemesThemeId");

                    b.ToTable("SpecialityTheme");
                });

            modelBuilder.Entity("TestWpfApp.Data.DataModels.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ThemeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupId");

                    b.HasIndex("ThemeId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("TestWpfApp.Data.DataModels.Speciality", b =>
                {
                    b.Property<int>("SpecialityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SpecialityId");

                    b.ToTable("Specialities");
                });

            modelBuilder.Entity("TestWpfApp.Data.DataModels.SpecialityThemeSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionsCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecialityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThemeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SpecialityId");

                    b.HasIndex("ThemeId");

                    b.ToTable("SpecialityThemeSettings");
                });

            modelBuilder.Entity("TestWpfApp.Data.DataModels.TestQuestion", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageQuestion")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ImageQuestionBytes")
                        .HasColumnType("BLOB");

                    b.Property<string>("NameAnswerCorrect1")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameAnswerIncorrect1")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameAnswerIncorrect2")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameAnswerIncorrect3")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameArticle")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameQuestion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameSpeciality")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameTheme")
                        .HasColumnType("TEXT");

                    b.Property<int>("ThemeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("QuestionId");

                    b.HasIndex("ThemeId");

                    b.ToTable("TestQuestions");
                });

            modelBuilder.Entity("TestWpfApp.Data.DataModels.Theme", b =>
                {
                    b.Property<int>("ThemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ThemeId");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("GroupSpeciality", b =>
                {
                    b.HasOne("TestWpfApp.Data.DataModels.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestWpfApp.Data.DataModels.Speciality", null)
                        .WithMany()
                        .HasForeignKey("SpecialitiesSpecialityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpecialityTheme", b =>
                {
                    b.HasOne("TestWpfApp.Data.DataModels.Speciality", null)
                        .WithMany()
                        .HasForeignKey("SpecialitiesSpecialityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestWpfApp.Data.DataModels.Theme", null)
                        .WithMany()
                        .HasForeignKey("ThemesThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestWpfApp.Data.DataModels.Group", b =>
                {
                    b.HasOne("TestWpfApp.Data.DataModels.Theme", null)
                        .WithMany("Groups")
                        .HasForeignKey("ThemeId");
                });

            modelBuilder.Entity("TestWpfApp.Data.DataModels.SpecialityThemeSetting", b =>
                {
                    b.HasOne("TestWpfApp.Data.DataModels.Speciality", "Speciality")
                        .WithMany("ThemeSettings")
                        .HasForeignKey("SpecialityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestWpfApp.Data.DataModels.Theme", "Theme")
                        .WithMany()
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Speciality");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("TestWpfApp.Data.DataModels.TestQuestion", b =>
                {
                    b.HasOne("TestWpfApp.Data.DataModels.Theme", "Theme")
                        .WithMany("Questions")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("TestWpfApp.Data.DataModels.Speciality", b =>
                {
                    b.Navigation("ThemeSettings");
                });

            modelBuilder.Entity("TestWpfApp.Data.DataModels.Theme", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
