// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestWpfApp.Data.Context;

#nullable disable

namespace TestWpfApp.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("GroupDataModelSpecialityDataModel", b =>
                {
                    b.Property<int>("GroupsDataModelGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecialitysDataModelSpecialityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupsDataModelGroupId", "SpecialitysDataModelSpecialityId");

                    b.HasIndex("SpecialitysDataModelSpecialityId");

                    b.ToTable("GroupDataModelSpecialityDataModel");
                });

            modelBuilder.Entity("SpecialityDataModelThemeDataModel", b =>
                {
                    b.Property<int>("SpecialitysDataModelSpecialityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThemesDataModelThemeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SpecialitysDataModelSpecialityId", "ThemesDataModelThemeId");

                    b.HasIndex("ThemesDataModelThemeId");

                    b.ToTable("SpecialityDataModelThemeDataModel");
                });

            modelBuilder.Entity("TestWpfApp.Data.DataModels.GroupDataModel", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameGroup")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ThemeDataModelThemeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupId");

                    b.HasIndex("ThemeDataModelThemeId");

                    b.ToTable("GroupDataModels");
                });

            modelBuilder.Entity("TestWpfApp.Data.DataModels.SettingsSpecialityDataModel", b =>
                {
                    b.Property<int>("SettingsSpecialityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumberQuestionsInTheme")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpecialityDataModelSpecialityId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ThemeDataModelThemeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SettingsSpecialityId");

                    b.HasIndex("SpecialityDataModelSpecialityId");

                    b.HasIndex("ThemeDataModelThemeId");

                    b.ToTable("SettingsSpecialityDataModel");
                });

            modelBuilder.Entity("TestWpfApp.Data.DataModels.SpecialityDataModel", b =>
                {
                    b.Property<int>("SpecialityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameSpeciality")
                        .HasColumnType("TEXT");

                    b.HasKey("SpecialityId");

                    b.ToTable("SpecialityDataModels");
                });

            modelBuilder.Entity("TestWpfApp.Data.DataModels.TestQuestionDataModel", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageQuestion")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ImageQuestionBytes")
                        .HasColumnType("BLOB");

                    b.Property<string>("NameAnswerCorrect1")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameAnswerIncorrect1")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameAnswerIncorrect2")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameAnswerIncorrect3")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameArticle")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameQuestion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameSpeciality")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameTheme")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ThemeDataModelThemeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ThemeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("QuestionId");

                    b.HasIndex("ThemeDataModelThemeId");

                    b.ToTable("TestQuestionDataModels");
                });

            modelBuilder.Entity("TestWpfApp.Data.DataModels.ThemeDataModel", b =>
                {
                    b.Property<int>("ThemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameTheme")
                        .HasColumnType("TEXT");

                    b.HasKey("ThemeId");

                    b.ToTable("ThemeDataModels");
                });

            modelBuilder.Entity("GroupDataModelSpecialityDataModel", b =>
                {
                    b.HasOne("TestWpfApp.Data.DataModels.GroupDataModel", null)
                        .WithMany()
                        .HasForeignKey("GroupsDataModelGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestWpfApp.Data.DataModels.SpecialityDataModel", null)
                        .WithMany()
                        .HasForeignKey("SpecialitysDataModelSpecialityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpecialityDataModelThemeDataModel", b =>
                {
                    b.HasOne("TestWpfApp.Data.DataModels.SpecialityDataModel", null)
                        .WithMany()
                        .HasForeignKey("SpecialitysDataModelSpecialityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestWpfApp.Data.DataModels.ThemeDataModel", null)
                        .WithMany()
                        .HasForeignKey("ThemesDataModelThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestWpfApp.Data.DataModels.GroupDataModel", b =>
                {
                    b.HasOne("TestWpfApp.Data.DataModels.ThemeDataModel", null)
                        .WithMany("GroupsDataModel")
                        .HasForeignKey("ThemeDataModelThemeId");
                });

            modelBuilder.Entity("TestWpfApp.Data.DataModels.SettingsSpecialityDataModel", b =>
                {
                    b.HasOne("TestWpfApp.Data.DataModels.SpecialityDataModel", null)
                        .WithMany("SettingsSpecialitysDataModel")
                        .HasForeignKey("SpecialityDataModelSpecialityId");

                    b.HasOne("TestWpfApp.Data.DataModels.ThemeDataModel", "ThemeDataModel")
                        .WithMany()
                        .HasForeignKey("ThemeDataModelThemeId");

                    b.Navigation("ThemeDataModel");
                });

            modelBuilder.Entity("TestWpfApp.Data.DataModels.TestQuestionDataModel", b =>
                {
                    b.HasOne("TestWpfApp.Data.DataModels.ThemeDataModel", "ThemeDataModel")
                        .WithMany("QuestionsDataModel")
                        .HasForeignKey("ThemeDataModelThemeId");

                    b.Navigation("ThemeDataModel");
                });

            modelBuilder.Entity("TestWpfApp.Data.DataModels.SpecialityDataModel", b =>
                {
                    b.Navigation("SettingsSpecialitysDataModel");
                });

            modelBuilder.Entity("TestWpfApp.Data.DataModels.ThemeDataModel", b =>
                {
                    b.Navigation("GroupsDataModel");

                    b.Navigation("QuestionsDataModel");
                });
#pragma warning restore 612, 618
        }
    }
}
